---
openapi: 3.0.1
info:
  title: Book.it API
  version: v1
paths:
  "/vehicles":
    get:
      summary: list vehicles
      tags:
      - Vehicles
      responses:
        '200':
          description: successful
    post:
      summary: create vehicle
      tags:
      - Vehicles
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                  format: float
                image:
                  type: string
                visible:
                  type: boolean
              required:
              - name
              - price
              - image
              - visible
  "/vehicles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show vehicle
      tags:
      - Vehicles
      responses:
        '200':
          description: successful
    patch:
      summary: update vehicle
      tags:
      - Vehicles
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:4000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
