---
openapi: 3.0.1
info:
  title: Book.it API
  version: v1
paths:
  "/reservations":
    get:
      summary: list reservations
      tags:
      - Reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      tags:
      - Reservations
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date
                city:
                  type: string
                vehicle_id:
                  type: integer
                user_id:
                  type: integer
              required:
              - date
              - city
              - vehicle_id
              - user_id
  "/users/sign_up":
    get:
      summary: new registration
      tags:
      - User Registrations
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  pattern: "^\\S+@\\S+\\.\\S+$"
                  format: email
                role:
                  type: string
                password:
                  type: string
                  format: password
                password_confirmation:
                  type: string
                  format: password
              required:
              - username
              - email
              - role
              - password
              - password_confirmation
  "/users/sign_in":
    post:
      summary: create session
      tags:
      - Users Sessions
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  pattern: "^\\S+@\\S+\\.\\S+$"
                  format: email
                password:
                  type: string
                  format: password
              required:
              - email
              - password
  "/users/sign_out":
    delete:
      summary: delete session
      tags:
      - Users Sessions
      responses:
        '200':
          description: successful
  "/vehicles":
    get:
      summary: list vehicles
      tags:
      - Vehicles
      responses:
        '200':
          description: successful
    post:
      summary: create vehicle
      tags:
      - Vehicles
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                  format: float
                image:
                  type: string
                visible:
                  type: boolean
              required:
              - name
              - price
              - image
              - visible
  "/vehicles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show vehicle
      tags:
      - Vehicles
      responses:
        '200':
          description: successful
    patch:
      summary: update vehicle
      tags:
      - Vehicles
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:4000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
